In [1]:
import pandas as pd
import numpy as np
import os
from plantcv import plantcv as pcv

In [2]:
# Enter path to the data_fusion_guest_lecture file
image_folder_path = r"C:\Users\Fivos\Desktop\Data Fusion\Project\data"

In [3]:
# Loads labels
df = pd.read_csv(os.path.join(image_folder_path, "seedling_labels.csv"))

In [4]:
df

,Expert 1,Expert 2,Expert 3,Expert 4,color_cam_path,side_cam_path,Rfid,Pos
0,4,4,4,4,A1/00387 Plant 0000 Plant 0000/18-02-2019 -- 1...,A1/00387 Plant 0000 Plant 0000/18-02-2019 -- 1...,A1,Plant 0000
1,1,1,1,1,A1/00388 Plant 0001 Plant 0001/18-02-2019 -- 1...,A1/00388 Plant 0001 Plant 0001/18-02-2019 -- 1...,A1,Plant 0001
2,1,1,1,1,A1/00389 Plant 0002 Plant 0002/18-02-2019 -- 1...,A1/00389 Plant 0002 Plant 0002/18-02-2019 -- 1...,A1,Plant 0002
3,4,4,3,3,A1/00390 Plant 0003 Plant 0003/18-02-2019 -- 1...,A1/00390 Plant 0003 Plant 0003/18-02-2019 -- 1...,A1,Plant 0003
4,3,1,1,1,A1/00391 Plant 0004 Plant 0004/18-02-2019 -- 1...,A1/00391 Plant 0004 Plant 0004/18-02-2019 -- 1...,A1,Plant 0004
...,...,...,...,...,...,...,...,...
989,1,1,1,1,B4/01019 Plant 0122 Plant 0122/18-02-2019 -- 1...,B4/01019 Plant 0122 Plant 0122/18-02-2019 -- 1...,B4,Plant 0122
990,1,1,1,1,B4/01020 Plant 0123 Plant 0123/18-02-2019 -- 1...,B4/01020 Plant 0123 Plant 0123/18-02-2019 -- 1...,B4,Plant 0123
991,1,1,1,1,B4/01021 Plant 0124 Plant 0124/18-02-2019 -- 1...,B4/01021 Plant 0124 Plant 0124/18-02-2019 -- 1...,B4,Plant 0124
992,2,3,3,3,B4/01022 Plant 0125 Plant 0125/18-02-2019 -- 1...,B4/01022 Plant 0125 Plant 0125/18-02-2019 -- 1...,B4,Plant 0125
993,3,3,3,3,B4/01023 Plant 0126 Plant 0126/18-02-2019 -- 1...,B4/01023 Plant 0126 Plant 0126/18-02-2019 -- 1...,B4,Plant 0126

In [5]:
# Creates path to top 
df["color_cam_path"] = image_folder_path + "/" + df["color_cam_path"]

# Gives average expert label as a starting point
df["average_expert"] = (df["Expert 1"] + df["Expert 2"]  + df["Expert 3"] + df["Expert 4"]) / 4
df

,Expert 1,Expert 2,Expert 3,Expert 4,color_cam_path,side_cam_path,Rfid,Pos,average_expert
0,4,4,4,4,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,A1/00387 Plant 0000 Plant 0000/18-02-2019 -- 1...,A1,Plant 0000,4.00
1,1,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,A1/00388 Plant 0001 Plant 0001/18-02-2019 -- 1...,A1,Plant 0001,1.00
2,1,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,A1/00389 Plant 0002 Plant 0002/18-02-2019 -- 1...,A1,Plant 0002,1.00
3,4,4,3,3,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,A1/00390 Plant 0003 Plant 0003/18-02-2019 -- 1...,A1,Plant 0003,3.50
4,3,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,A1/00391 Plant 0004 Plant 0004/18-02-2019 -- 1...,A1,Plant 0004,1.50
...,...,...,...,...,...,...,...,...,...
989,1,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,B4/01019 Plant 0122 Plant 0122/18-02-2019 -- 1...,B4,Plant 0122,1.00
990,1,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,B4/01020 Plant 0123 Plant 0123/18-02-2019 -- 1...,B4,Plant 0123,1.00
991,1,1,1,1,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,B4/01021 Plant 0124 Plant 0124/18-02-2019 -- 1...,B4,Plant 0124,1.00
992,2,3,3,3,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,B4/01022 Plant 0125 Plant 0125/18-02-2019 -- 1...,B4,Plant 0125,2.75
993,3,3,3,3,C:\Users\Fivos\Desktop\Data Fusion\Project\dat...,B4/01023 Plant 0126 Plant 0126/18-02-2019 -- 1...,B4,Plant 0126,3.00

In [6]:
total_color_df = pd.DataFrame()
count = 0

for path in df["color_cam_path"]:
    class options:
        def __init__(self):
            self.image = path
            #self.debug = "print"
            self.writeimg= False
            self.result = "VIS_test_results.json"
            self.outdir = "." # Store the output to the folder inside the current working directory
    # Get options
    args = options()

    # Set debug to the global parameter 
    #pcv.params.debug = args.debug
    
    # Read image
    img, path, filename = pcv.readimage(filename=args.image)
    
    # Convert RGB to HSV and extract the saturation channel
    s = pcv.rgb2gray_hsv(rgb_img=img, channel='s')
    
    # Take a binary threshold to separate plant from background. 
    s_thresh = pcv.threshold.binary(gray_img=s, threshold=125, max_value=255, object_type='light')

    # Median Blur to clean noise 
    s_mblur = pcv.median_blur(gray_img=s_thresh, ksize=9)

    # Convert RGB to LAB and extract the blue channel ('b')
    # Threshold the blue channel image 
    b = pcv.rgb2gray_lab(rgb_img=img, channel='b')
    b_thresh = pcv.threshold.binary(gray_img=b, threshold=160, max_value=255, 
                                object_type='light')
    
    # Join the threshold saturation and blue-yellow images with a logical or operation 
    bs = pcv.logical_or(bin_img1=s_mblur, bin_img2=b_thresh)
    
    # Appy Mask (for VIS images, mask_color='white')
    masked = pcv.apply_mask(img=img, mask=bs, mask_color='white')
    
    # Convert RGB to LAB and extract the Green-Magenta and Blue-Yellow channels
    masked_a = pcv.rgb2gray_lab(rgb_img=masked, channel='a')
    masked_b = pcv.rgb2gray_lab(rgb_img=masked, channel='b')
    
    # Threshold the green-magenta and blue images
    maskeda_thresh = pcv.threshold.binary(gray_img=masked_a, threshold=119, 
                                      max_value=255, object_type='dark')

    maskedb_thresh = pcv.threshold.binary(gray_img=masked_b, threshold=180, 
                                      max_value=255, object_type='light')
    
    # Join the thresholded saturation and blue-yellow images (OR)
    ab = pcv.logical_or(bin_img1=maskeda_thresh, bin_img2=maskedb_thresh)
    
    # Opening filters out bright noise from an image.
    opened_ab = pcv.opening(gray_img=ab)
    
    # Fill small objects (reduce image noise) 
    ab_fill = pcv.fill(bin_img=ab, size=400)
    
    # Closing filters out dark noise from an image.
    closed_ab = pcv.closing(gray_img=ab_fill)
    
    # Apply mask (for VIS images, mask_color=white)
    masked2 = pcv.apply_mask(img=masked, mask=ab_fill, mask_color='white')

    # Identify objects
    id_objects, obj_hierarchy = pcv.find_objects(img=masked2, mask=ab_fill)
    
    # Define the region of interest (ROI) 
    roi1, roi_hierarchy= pcv.roi.rectangle(img=masked2, x=200, y=80, h=650, w=1050)
    
    # Decide which objects to keep
    roi_objects, hierarchy3, kept_mask, obj_area = pcv.roi_objects(img=img, roi_contour=roi1, 
                                                               roi_hierarchy=roi_hierarchy, 
                                                               object_contour=id_objects, 
                                                               obj_hierarchy=obj_hierarchy,
                                                               roi_type='partial')
    
    # Object combine kept objects
    obj, mask = pcv.object_composition(img=img, contours=roi_objects, hierarchy=hierarchy3)

    # Find shape properties, data gets stored to an Outputs class automatically
    analysis_image = pcv.analyze_object(img=img, obj=obj, mask=mask, label="default")
    
    # Determine color properties: Histograms, Color Slices and Pseudocolored Images, output color analyzed images (optional)
    color_histogram = pcv.analyze_color(rgb_img=img, mask=kept_mask, colorspaces='all', label="default")

    # Divide plant object into twenty equidistant bins and assign pseudolandmark points based upon their 
    # actual (not scaled) position. Once this data is scaled this approach may provide some information 
    # regarding shape independent of size.
    top_x, bottom_x, center_v_x = pcv.x_axis_pseudolandmarks(img=img, obj=obj, mask=mask, label="default")
    top_y, bottom_y, center_v_y = pcv.y_axis_pseudolandmarks(img=img, obj=obj, mask=mask)
    
    pcv.outputs.save_results(filename=args.result)
    results_json = pd.read_json(args.result)['observations'][0]
    df_results = pd.DataFrame(results_json)

    # Keep the values of the features as well as the column names
    feature_values = df_results.iloc[[4]]

    # Turn the lists into individual columns 
    for i in range(len(feature_values.iloc[0])):
        if isinstance(feature_values.iloc[0][i],list):
            column_names = [feature_values.columns.values[i]+'{}'.format(x) for x in range(len(feature_values.iloc[0][i]))]
            new_df = pd.DataFrame([feature_values.iloc[0][i]],columns = column_names )
            feature_values = pd.concat([feature_values.drop(feature_values.columns.values[i], axis=1), new_df.set_axis(feature_values.index)], axis=1)

    total_color_df = total_color_df.append(feature_values,ignore_index = True)
    print("Count is "+ str(count))
    count +=1

Count is 0
Count is 1
Count is 2
Count is 3
Count is 4
Count is 5
Count is 6
Count is 7
Count is 8
Count is 9
Count is 10
Count is 11
Count is 12
Count is 13
Count is 14
Count is 15
Count is 16
Count is 17
Count is 18
Count is 19
Count is 20
Count is 21
Count is 22
Count is 23
Count is 24
Count is 25
Count is 26
Count is 27
Count is 28
Count is 29
Count is 30
Count is 31
Count is 32
Count is 33
Count is 34
Count is 35
Count is 36
Count is 37
Count is 38
Count is 39
Count is 40
Count is 41
Count is 42
Count is 43
Count is 44
Count is 45
Count is 46
Count is 47
Count is 48
Count is 49
Count is 50
Count is 51
Count is 52
Count is 53
Count is 54
Count is 55
Count is 56
Count is 57
Count is 58
Count is 59
Count is 60
Count is 61
Count is 62
Count is 63
Count is 64
Count is 65
Count is 66
Count is 67
Count is 68
Count is 69
Count is 70
Count is 71
Count is 72
Count is 73
Count is 74
Count is 75
Count is 76
Count is 77
Count is 78
Count is 79
Count is 80
Count is 81
Count is 82
Count is 83
Count is 84
Count is 85
Count is 86
Count is 87
Count is 88
Count is 89
Count is 90
Count is 91
Count is 92
Count is 93
Count is 94
Count is 95
Count is 96
Count is 97
Count is 98
Count is 99
Count is 100
Count is 101
Count is 102
Count is 103
Count is 104
Count is 105
Count is 106
Count is 107
Count is 108
Count is 109
Count is 110
Count is 111
Count is 112
Count is 113
Count is 114
Count is 115
Count is 116
Count is 117
Count is 118
Count is 119
Count is 120
Count is 121
Count is 122
Count is 123
Count is 124
Count is 125
Count is 126
Count is 127
Count is 128
Count is 129
Count is 130
Count is 131
Count is 132
Count is 133
Count is 134
Count is 135
Count is 136
Count is 137
Count is 138
Count is 139
Count is 140
Count is 141
Count is 142
Count is 143
Count is 144
Count is 145
Count is 146
Count is 147
Count is 148
Count is 149
Count is 150
Count is 151
Count is 152
Count is 153
Count is 154
Count is 155
Count is 156
Count is 157
Count is 158
Count is 159
Count is 160
Count is 161
Count is 162
Count is 163
Count is 164
Count is 165
Count is 166
Count is 167
Count is 168
Count is 169
Count is 170
Count is 171
Count is 172
Count is 173
Count is 174
Count is 175
Count is 176
Count is 177
Count is 178
Count is 179
Count is 180
Count is 181
Count is 182
Count is 183
Count is 184
Count is 185
Count is 186
Count is 187
Count is 188
Count is 189
Count is 190
Count is 191
Count is 192
Count is 193
Count is 194
Count is 195
Count is 196
Count is 197
Count is 198
Count is 199
Count is 200
Count is 201
Count is 202
Count is 203
Count is 204
Count is 205
Count is 206
Count is 207
Count is 208
Count is 209
Count is 210
Count is 211
Count is 212
Count is 213
Count is 214
Count is 215
Count is 216
Count is 217
Count is 218
Count is 219
Count is 220
Count is 221
Count is 222
Count is 223
Count is 224
Count is 225
Count is 226
Count is 227
Count is 228
Count is 229
Count is 230
Count is 231
Count is 232
Count is 233
Count is 234
Count is 235
Count is 236
Count is 237
Count is 238
Count is 239
Count is 240
Count is 241
Count is 242
Count is 243
Count is 244
Count is 245
Count is 246
Count is 247
Count is 248
Count is 249
Count is 250
Count is 251
Count is 252
Count is 253
Count is 254
Count is 255
Count is 256
Count is 257
Count is 258
Count is 259
Count is 260
Count is 261
Count is 262
Count is 263
Count is 264
Count is 265
Count is 266
Count is 267
Count is 268
Count is 269
Count is 270
Count is 271
Count is 272
Count is 273
Count is 274
Count is 275
Count is 276
Count is 277
Count is 278
Count is 279
Count is 280
Count is 281
Count is 282
Count is 283
Count is 284
Count is 285
Count is 286
Count is 287
Count is 288
Count is 289
Count is 290
Count is 291
Count is 292
Count is 293
Count is 294
Count is 295
Count is 296
Count is 297
Count is 298
Count is 299
Count is 300
Count is 301
Count is 302
Count is 303
Count is 304
Count is 305
Count is 306
Count is 307
Count is 308
Count is 309
Count is 310
Count is 311
Count is 312
Count is 313
Count is 314
Count is 315
Count is 316
Count is 317
Count is 318
Count is 319
Count is 320
Count is 321
Count is 322
Count is 323
Count is 324
Count is 325
Count is 326
Count is 327
Count is 328
Count is 329
Count is 330
Count is 331
Count is 332
Count is 333
Count is 334
Count is 335
Count is 336
Count is 337
Count is 338
Count is 339
Count is 340
Count is 341
Count is 342
Count is 343
Count is 344
Count is 345
Count is 346
Count is 347
Count is 348
Count is 349
Count is 350
Count is 351
Count is 352
Count is 353
Count is 354
Count is 355
Count is 356
Count is 357
Count is 358
Count is 359
Count is 360
Count is 361
Count is 362
Count is 363
Count is 364
Count is 365
Count is 366
Count is 367
Count is 368
Count is 369
Count is 370
Count is 371
Count is 372
Count is 373
Count is 374
Count is 375
Count is 376
Count is 377
Count is 378
Count is 379
Count is 380
Count is 381
Count is 382
Count is 383
Count is 384
Count is 385
Count is 386
Count is 387
Count is 388
Count is 389
Count is 390
Count is 391
Count is 392
Count is 393
Count is 394
Count is 395
Count is 396
Count is 397
Count is 398
Count is 399
Count is 400
Count is 401
Count is 402
Count is 403
Count is 404
Count is 405
Count is 406
Count is 407
Count is 408
Count is 409
Count is 410
Count is 411
Count is 412
Count is 413
Count is 414
Count is 415
Count is 416
Count is 417
Count is 418
Count is 419
Count is 420
Count is 421
Count is 422
Count is 423
Count is 424
Count is 425
Count is 426
Count is 427
Count is 428
Count is 429
Count is 430
Count is 431
Count is 432
Count is 433
Count is 434
Count is 435
Count is 436
Count is 437
Count is 438
Count is 439
Count is 440
Count is 441
Count is 442
Count is 443
Count is 444
Count is 445
Count is 446
Count is 447
Count is 448
Count is 449
Count is 450
Count is 451
Count is 452
Count is 453
Count is 454
Count is 455
Count is 456
Count is 457
Count is 458
Count is 459
Count is 460
Count is 461
Count is 462
Count is 463
Count is 464
Count is 465
Count is 466
Count is 467
Count is 468
Count is 469
Count is 470
Count is 471
Count is 472
Count is 473
Count is 474
Count is 475
Count is 476
Count is 477
Count is 478
Count is 479
Count is 480
Count is 481
Count is 482
Count is 483
Count is 484
Count is 485
Count is 486
Count is 487
Count is 488
Count is 489
Count is 490
Count is 491
Count is 492
Count is 493
Count is 494
Count is 495
Count is 496
Count is 497
Count is 498
Count is 499
Count is 500
Count is 501
Count is 502
Count is 503
Count is 504
Count is 505
Count is 506
Count is 507
Count is 508
Count is 509
Count is 510
Count is 511
Count is 512
Count is 513
Count is 514
Count is 515
Count is 516
Count is 517
Count is 518
Count is 519
Count is 520
Count is 521
Count is 522
Count is 523
Count is 524
Count is 525
Count is 526
Count is 527
Count is 528
Count is 529
Count is 530
Count is 531
Count is 532
Count is 533
Count is 534
Count is 535
Count is 536
Count is 537
Count is 538
Count is 539
Count is 540
Count is 541
Count is 542
Count is 543
Count is 544
Count is 545
Count is 546
Count is 547
Count is 548
Count is 549
Count is 550
Count is 551
Count is 552
Count is 553
Count is 554
Count is 555
Count is 556
Count is 557
Count is 558
Count is 559
Count is 560
Count is 561
Count is 562
Count is 563
Count is 564
Count is 565
Count is 566
Count is 567
Count is 568
Count is 569
Count is 570
Count is 571
Count is 572
Count is 573
Count is 574
Count is 575
Count is 576
Count is 577
Count is 578
Count is 579
Count is 580
Count is 581
Count is 582
Count is 583
Count is 584
Count is 585
Count is 586
Count is 587
Count is 588
Count is 589
Count is 590
Count is 591
Count is 592
Count is 593
Count is 594
Count is 595
Count is 596
Count is 597
Count is 598
Count is 599
Count is 600
Count is 601
Count is 602
Count is 603
Count is 604
Count is 605
Count is 606
Count is 607
Count is 608
Count is 609
Count is 610
Count is 611
Count is 612
Count is 613
Count is 614
Count is 615
Count is 616
Count is 617
Count is 618
Count is 619
Count is 620
Count is 621
Count is 622
Count is 623
Count is 624
Count is 625
Count is 626
Count is 627
Count is 628
Count is 629
Count is 630
Count is 631
Count is 632
Count is 633
Count is 634
Count is 635
Count is 636
Count is 637
Count is 638

Count is 639
Count is 640
Count is 641
Count is 642
Count is 643
Count is 644
Count is 645
Count is 646
Count is 647
Count is 648
Count is 649
Count is 650
Count is 651
Count is 652
Count is 653
Count is 654
Count is 655
Count is 656
Count is 657
Count is 658
Count is 659
Count is 660
Count is 661
Count is 662
Count is 663
Count is 664
Count is 665
Count is 666
Count is 667
Count is 668
Count is 669
Count is 670
Count is 671
Count is 672
Count is 673
Count is 674
Count is 675
Count is 676
Count is 677
Count is 678
Count is 679
Count is 680
Count is 681
Count is 682
Count is 683
Count is 684
Count is 685
Count is 686
Count is 687
Count is 688
Count is 689
Count is 690
Count is 691
Count is 692
Count is 693
Count is 694
Count is 695
Count is 696
Count is 697
Count is 698
Count is 699
Count is 700
Count is 701
Count is 702
Count is 703
Count is 704
Count is 705
Count is 706
Count is 707
Count is 708
Count is 709
Count is 710
Count is 711
Count is 712
Count is 713
Count is 714
Count is 715
Count is 716
Count is 717
Count is 718
Count is 719
Count is 720
Count is 721
Count is 722
Count is 723
Count is 724
Count is 725
Count is 726
Count is 727
Count is 728
Count is 729
Count is 730
Count is 731
Count is 732
Count is 733
Count is 734
Count is 735
Count is 736
Count is 737
Count is 738
Count is 739
Count is 740
Count is 741
Count is 742
Count is 743
Count is 744
Count is 745
Count is 746
Count is 747
Count is 748
Count is 749
Count is 750
Count is 751
Count is 752
Count is 753
Count is 754
Count is 755
Count is 756
Count is 757
Count is 758
Count is 759
Count is 760
Count is 761
Count is 762
Count is 763
Count is 764
Count is 765
Count is 766
Count is 767
Count is 768
Count is 769
Count is 770
Count is 771
Count is 772
Count is 773
Count is 774
Count is 775
Count is 776
Count is 777
Count is 778
Count is 779
Count is 780
Count is 781
Count is 782
Count is 783
Count is 784
Count is 785
Count is 786
Count is 787
Count is 788
Count is 789
Count is 790
Count is 791
Count is 792
Count is 793
Count is 794
Count is 795
Count is 796
Count is 797
Count is 798
Count is 799
Count is 800
Count is 801
Count is 802
Count is 803
Count is 804
Count is 805
Count is 806
Count is 807
Count is 808
Count is 809
Count is 810
Count is 811
Count is 812
Count is 813
Count is 814
Count is 815
Count is 816
Count is 817
Count is 818
Count is 819
Count is 820
Count is 821
Count is 822
Count is 823
Count is 824
Count is 825
Count is 826
Count is 827
Count is 828
Count is 829
Count is 830
Count is 831
Count is 832
Count is 833
Count is 834
Count is 835
Count is 836
Count is 837
Count is 838
Count is 839
Count is 840
Count is 841
Count is 842
Count is 843
Count is 844
Count is 845
Count is 846
Count is 847
Count is 848
Count is 849
Count is 850
Count is 851
Count is 852
Count is 853
Count is 854
Count is 855
Count is 856
Count is 857
Count is 858
Count is 859
Count is 860
Count is 861
Count is 862
Count is 863
Count is 864
Count is 865
Count is 866
Count is 867
Count is 868
Count is 869
Count is 870
Count is 871
Count is 872
Count is 873
Count is 874
Count is 875
Count is 876
Count is 877
Count is 878
Count is 879
Count is 880
Count is 881
Count is 882
Count is 883
Count is 884
Count is 885
Count is 886
Count is 887
Count is 888
Count is 889
Count is 890
Count is 891
Count is 892
Count is 893
Count is 894
Count is 895
Count is 896
Count is 897
Count is 898
Count is 899
Count is 900
Count is 901
Count is 902
Count is 903
Count is 904
Count is 905
Count is 906
Count is 907
Count is 908
Count is 909
Count is 910
Count is 911
Count is 912
Count is 913
Count is 914
Count is 915
Count is 916
Count is 917
Count is 918
Count is 919
Count is 920
Count is 921
Count is 922
Count is 923
Count is 924
Count is 925
Count is 926
Count is 927
Count is 928
Count is 929
Count is 930
Count is 931
Count is 932
Count is 933
Count is 934
Count is 935
Count is 936
Count is 937
Count is 938
Count is 939
Count is 940
Count is 941
Count is 942
Count is 943
Count is 944
Count is 945
Count is 946
Count is 947
Count is 948
Count is 949
Count is 950
Count is 951
Count is 952
Count is 953
Count is 954
Count is 955
Count is 956
Count is 957
Count is 958
Count is 959
Count is 960
Count is 961
Count is 962
Count is 963
Count is 964
Count is 965
Count is 966
Count is 967
Count is 968
Count is 969
Count is 970
Count is 971
Count is 972
Count is 973
Count is 974
Count is 975
Count is 976
Count is 977
Count is 978
Count is 979
Count is 980
Count is 981
Count is 982
Count is 983
Count is 984
Count is 985
Count is 986
Count is 987
Count is 988
Count is 989
Count is 990
Count is 991
Count is 992
Count is 993

In [7]:
# total runtime 42 min

In [8]:
total_color_df

,in_bounds,area,convex_hull_area,solidity,perimeter,width,height,longest_path,convex_hull_vertices,object_in_frame,...,right_lmk10,right_lmk11,right_lmk12,right_lmk13,right_lmk14,right_lmk15,right_lmk16,right_lmk17,right_lmk18,right_lmk19
0,True,4122,7526.5,0.547665,855.377,58,170,1071,18,True,...,"[656.0, 450.0]","[655.0, 458.0]","[674.0, 466.0]","[673.0, 474.0]","[670.0, 482.0]","[669.0, 490.0]","[665.0, 498.0]","[671.0, 506.0]","[671.0, 514.0]","[681.0, 522.0]"
1,True,106815,238795,0.447308,7549.37,657,587,4705,29,True,...,"[855.0, 386.0]","[875.0, 413.0]","[889.0, 440.0]","[749.0, 467.0]","[794.0, 494.0]","[731.0, 521.0]","[731.0, 548.0]","[723.0, 575.0]","[702.0, 602.0]","[676.0, 629.0]"
2,False,95816,250930,0.381844,5987.1,499,784,5539,33,False,...,"[860.0, 564.0]","[893.0, 601.0]","[921.0, 638.0]","[934.0, 675.0]","[938.0, 712.0]","[935.0, 749.0]","[924.0, 786.0]","[902.0, 823.0]","[881.0, 860.0]","[857.0, 897.0]"
3,True,7352,15247.5,0.482177,961.703,129,210,1327,13,True,...,"[679.0, 471.0]","[676.0, 481.0]","[684.0, 491.0]","[683.0, 501.0]","[690.0, 511.0]","[690.0, 521.0]","[688.0, 531.0]","[692.0, 541.0]","[726.0, 551.0]","[756.0, 561.0]"
4,False,112481,274432,0.409869,8987.7,792,557,5531,23,False,...,"[1163.0, 360.0]","[1176.0, 386.0]","[1182.0, 412.0]","[1279.0, 438.0]","[1278.0, 464.0]","[1277.0, 490.0]","[1279.0, 516.0]","[1045.0, 542.0]","[1046.0, 568.0]","[1041.0, 594.0]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,True,38105,292126,0.13044,6934.33,651,712,4977,34,True,...,"[1052.0, 430.0]","[1076.0, 463.0]","[1119.0, 496.0]","[1153.0, 529.0]","[1168.0, 562.0]","[1178.0, 595.0]","[1178.0, 628.0]","[1162.0, 661.0]","[1144.0, 694.0]","[1129.0, 727.0]"
990,False,54355,293035,0.18549,9396.73,622,614,4919,31,False,...,"[1211.0, 304.0]","[1088.0, 333.0]","[1106.0, 362.0]","[1098.0, 391.0]","[1111.0, 420.0]","[1144.0, 449.0]","[1144.0, 478.0]","[1121.0, 507.0]","[1108.0, 536.0]","[1087.0, 565.0]"
991,True,96430,283814,0.339764,8379.7,612,674,5910,33,True,...,"[673.0, 395.0]","[999.0, 427.0]","[1061.0, 459.0]","[1094.0, 491.0]","[1103.0, 523.0]","[1114.0, 555.0]","[1121.0, 587.0]","[1124.0, 619.0]","[1122.0, 651.0]","[1118.0, 683.0]"
992,True,43339,137722,0.314686,5023.54,548,458,4057,31,True,...,"[987.0, 334.0]","[1013.0, 355.0]","[1038.0, 376.0]","[1054.0, 397.0]","[1068.0, 418.0]","[1056.0, 439.0]","[644.0, 460.0]","[656.0, 481.0]","[662.0, 502.0]","[666.0, 523.0]"
993,True,13149,71605.5,0.183631,2837.98,415,424,3070,23,True,...,"[683.0, 368.0]","[668.0, 388.0]","[657.0, 408.0]","[649.0, 428.0]","[652.0, 448.0]","[652.0, 468.0]","[657.0, 488.0]","[677.0, 508.0]","[666.0, 528.0]","[650.0, 548.0]"

In [9]:
# We notice that the dataset has some nested lists so we get rid of those

In [10]:
 # Turn the lists into individual columns 
#feature_values = pd.DataFrame()
full_df = pd.DataFrame()
for i in range(len(total_color_df)):
    feature_values = total_color_df.iloc[[i]]
    for j in range(len(feature_values.iloc[0])):
        if isinstance(feature_values.iloc[0][j],list):
                column_names = [feature_values.columns.values[j]+'_{}'.format(x) for x in range(len(feature_values.iloc[0][j]))]
                new_df = pd.DataFrame([feature_values.iloc[0][j]],columns = column_names )
                feature_values = pd.concat([feature_values.drop(feature_values.columns.values[j], axis=1), new_df.set_axis(feature_values.index)], axis=1)
    full_df = full_df.append(feature_values,ignore_index = True)

In [11]:
full_df

,in_bounds,area,convex_hull_area,solidity,perimeter,width,height,longest_path,convex_hull_vertices,object_in_frame,...,right_lmk10_0,right_lmk10_1,right_lmk12_0,right_lmk12_1,right_lmk14_0,right_lmk14_1,right_lmk16_0,right_lmk16_1,right_lmk18_0,right_lmk18_1
0,True,4122,7526.5,0.547665,855.377,58,170,1071,18,True,...,656.0,450.0,674.0,466.0,670.0,482.0,665.0,498.0,671.0,514.0
1,True,106815,238795,0.447308,7549.37,657,587,4705,29,True,...,855.0,386.0,889.0,440.0,794.0,494.0,731.0,548.0,702.0,602.0
2,False,95816,250930,0.381844,5987.1,499,784,5539,33,False,...,860.0,564.0,921.0,638.0,938.0,712.0,924.0,786.0,881.0,860.0
3,True,7352,15247.5,0.482177,961.703,129,210,1327,13,True,...,679.0,471.0,684.0,491.0,690.0,511.0,688.0,531.0,726.0,551.0
4,False,112481,274432,0.409869,8987.7,792,557,5531,23,False,...,1163.0,360.0,1182.0,412.0,1278.0,464.0,1279.0,516.0,1046.0,568.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,True,38105,292126,0.13044,6934.33,651,712,4977,34,True,...,1052.0,430.0,1119.0,496.0,1168.0,562.0,1178.0,628.0,1144.0,694.0
990,False,54355,293035,0.18549,9396.73,622,614,4919,31,False,...,1211.0,304.0,1106.0,362.0,1111.0,420.0,1144.0,478.0,1108.0,536.0
991,True,96430,283814,0.339764,8379.7,612,674,5910,33,True,...,673.0,395.0,1061.0,459.0,1103.0,523.0,1121.0,587.0,1122.0,651.0
992,True,43339,137722,0.314686,5023.54,548,458,4057,31,True,...,987.0,334.0,1038.0,376.0,1068.0,418.0,644.0,460.0,662.0,502.0
993,True,13149,71605.5,0.183631,2837.98,415,424,3070,23,True,...,683.0,368.0,657.0,408.0,652.0,448.0,657.0,488.0,666.0,528.0

In [12]:
full_df.to_csv('VIS_features.csv')