In [143]:
import pandas as pd

In [144]:
df_bw = pd.read_csv('Grayscale_features.csv',index_col = 0)
df_bw

,nir_mean,nir_median,nir_stdev,in_bounds,area,convex_hull_area,solidity,perimeter,width,height,...,nir_frequencies250,nir_frequencies251,nir_frequencies252,nir_frequencies253,nir_frequencies254,nir_frequencies255,center_of_mass0,center_of_mass1,ellipse_center0,ellipse_center1
0,37.554685,34.0,13.459041,True,3191.0,4068.0,0.784415,634.673527,174,37,...,0,0,0,0,0,0,661.206518,716.185208,672.862244,714.586426
1,60.327510,46.0,36.801379,True,45052.0,178591.0,0.252264,3044.372918,611,431,...,0,0,0,0,0,0,707.989257,478.745161,714.550110,528.597351
2,58.813832,44.0,37.958030,True,47715.0,148611.0,0.321073,2471.103805,411,477,...,0,0,0,0,0,0,658.262161,444.421042,576.378296,500.127045
3,84.551197,46.0,68.811036,True,5303.0,5899.5,0.898890,508.066015,219,38,...,0,0,0,0,0,0,684.715067,715.408637,682.368225,714.712585
4,62.046977,45.0,42.304119,True,62094.0,203417.0,0.305255,4020.970021,577,515,...,0,0,0,0,0,0,820.912020,431.798499,815.368896,505.041443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,60.908476,37.0,49.117656,True,95538.0,245156.5,0.389702,5324.429713,506,589,...,0,0,0,0,0,0,917.996043,424.606649,854.520020,449.581421
990,65.389568,44.0,47.992251,True,80217.0,206081.5,0.389249,4973.995415,507,657,...,0,0,0,0,0,0,878.042958,358.853310,848.194763,429.562134
991,68.491876,43.0,51.960883,True,75767.0,139274.5,0.544012,5135.419242,383,526,...,0,0,0,0,0,0,710.262291,451.283791,719.425110,465.478058
992,73.719007,47.0,52.950624,True,31620.0,77629.5,0.407319,3019.457420,281,403,...,0,0,0,0,0,0,741.120936,529.499273,724.179016,539.669312
993,64.519922,45.0,45.232740,True,19878.0,57668.0,0.344697,1732.060087,389,262,...,0,0,0,0,0,0,776.597394,597.696800,773.558167,609.145569

In [145]:
df_bw['in_bounds'].value_counts()

True     988
False      6
Name: in_bounds, dtype: int64

In [146]:
print(list(np.where(df_bw["in_bounds"] == False)))

[array([719, 826, 836, 919, 962, 982], dtype=int64)]

In [147]:
df_bw['object_in_frame'].value_counts()

True     988
False      6
Name: object_in_frame, dtype: int64

In [148]:
print(list(np.where(df_bw["object_in_frame"] == False)))

[array([719, 826, 836, 919, 962, 982], dtype=int64)]

In [149]:
# We remove those rows from the dataset

In [150]:
df_bw.drop([719, 826, 836, 919, 962, 982], axis=0, inplace=True)

In [151]:
# We also remove those two columns from the dataset since they all contain the same value

In [152]:
df_bw.drop(['in_bounds','object_in_frame'], axis=1, inplace=True)

In [153]:
df_bw

,nir_mean,nir_median,nir_stdev,area,convex_hull_area,solidity,perimeter,width,height,longest_path,...,nir_frequencies250,nir_frequencies251,nir_frequencies252,nir_frequencies253,nir_frequencies254,nir_frequencies255,center_of_mass0,center_of_mass1,ellipse_center0,ellipse_center1
0,37.554685,34.0,13.459041,3191.0,4068.0,0.784415,634.673527,174,37,1096,...,0,0,0,0,0,0,661.206518,716.185208,672.862244,714.586426
1,60.327510,46.0,36.801379,45052.0,178591.0,0.252264,3044.372918,611,431,4168,...,0,0,0,0,0,0,707.989257,478.745161,714.550110,528.597351
2,58.813832,44.0,37.958030,47715.0,148611.0,0.321073,2471.103805,411,477,3564,...,0,0,0,0,0,0,658.262161,444.421042,576.378296,500.127045
3,84.551197,46.0,68.811036,5303.0,5899.5,0.898890,508.066015,219,38,1412,...,0,0,0,0,0,0,684.715067,715.408637,682.368225,714.712585
4,62.046977,45.0,42.304119,62094.0,203417.0,0.305255,4020.970021,577,515,3904,...,0,0,0,0,0,0,820.912020,431.798499,815.368896,505.041443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,60.908476,37.0,49.117656,95538.0,245156.5,0.389702,5324.429713,506,589,4798,...,0,0,0,0,0,0,917.996043,424.606649,854.520020,449.581421
990,65.389568,44.0,47.992251,80217.0,206081.5,0.389249,4973.995415,507,657,4816,...,0,0,0,0,0,0,878.042958,358.853310,848.194763,429.562134
991,68.491876,43.0,51.960883,75767.0,139274.5,0.544012,5135.419242,383,526,3743,...,0,0,0,0,0,0,710.262291,451.283791,719.425110,465.478058
992,73.719007,47.0,52.950624,31620.0,77629.5,0.407319,3019.457420,281,403,3122,...,0,0,0,0,0,0,741.120936,529.499273,724.179016,539.669312
993,64.519922,45.0,45.232740,19878.0,57668.0,0.344697,1732.060087,389,262,2879,...,0,0,0,0,0,0,776.597394,597.696800,773.558167,609.145569

In [154]:
# Check to see which columns are full of zeros

In [155]:
zero_index = []
for k in range(256):
    if (len(df_bw['nir_frequencies{}'.format(k)].value_counts()) == 1):
        zero_index.append(k)
        print(k,'occurencies of the value:', df_bw['nir_frequencies{}'.format(k)].value_counts().index.tolist())

0 occurencies of the value: [0]
1 occurencies of the value: [0]
2 occurencies of the value: [0]
3 occurencies of the value: [0]
4 occurencies of the value: [0]
5 occurencies of the value: [0]
6 occurencies of the value: [0]
7 occurencies of the value: [0]
8 occurencies of the value: [0]
9 occurencies of the value: [0]
10 occurencies of the value: [0]
215 occurencies of the value: [0]
217 occurencies of the value: [0]
218 occurencies of the value: [0]
219 occurencies of the value: [0]
220 occurencies of the value: [0]
221 occurencies of the value: [0]
222 occurencies of the value: [0]
223 occurencies of the value: [0]
224 occurencies of the value: [0]
225 occurencies of the value: [0]
226 occurencies of the value: [0]
227 occurencies of the value: [0]
228 occurencies of the value: [0]
229 occurencies of the value: [0]
230 occurencies of the value: [0]
231 occurencies of the value: [0]
232 occurencies of the value: [0]
233 occurencies of the value: [0]
234 occurencies of the value: [0]
235 occurencies of the value: [0]
236 occurencies of the value: [0]
237 occurencies of the value: [0]
238 occurencies of the value: [0]
239 occurencies of the value: [0]
240 occurencies of the value: [0]
241 occurencies of the value: [0]
242 occurencies of the value: [0]
243 occurencies of the value: [0]
244 occurencies of the value: [0]
245 occurencies of the value: [0]
246 occurencies of the value: [0]
247 occurencies of the value: [0]
248 occurencies of the value: [0]
249 occurencies of the value: [0]
250 occurencies of the value: [0]
251 occurencies of the value: [0]
252 occurencies of the value: [0]
253 occurencies of the value: [0]
254 occurencies of the value: [0]
255 occurencies of the value: [0]

In [156]:
zero_index

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 215,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255]

In [157]:
# We remove those from the dataset

In [158]:
name_list = []
for number in zero_index:
    name_list.append('nir_frequencies{}'.format(number))
name_list

['nir_frequencies0',
 'nir_frequencies1',
 'nir_frequencies2',
 'nir_frequencies3',
 'nir_frequencies4',
 'nir_frequencies5',
 'nir_frequencies6',
 'nir_frequencies7',
 'nir_frequencies8',
 'nir_frequencies9',
 'nir_frequencies10',
 'nir_frequencies215',
 'nir_frequencies217',
 'nir_frequencies218',
 'nir_frequencies219',
 'nir_frequencies220',
 'nir_frequencies221',
 'nir_frequencies222',
 'nir_frequencies223',
 'nir_frequencies224',
 'nir_frequencies225',
 'nir_frequencies226',
 'nir_frequencies227',
 'nir_frequencies228',
 'nir_frequencies229',
 'nir_frequencies230',
 'nir_frequencies231',
 'nir_frequencies232',
 'nir_frequencies233',
 'nir_frequencies234',
 'nir_frequencies235',
 'nir_frequencies236',
 'nir_frequencies237',
 'nir_frequencies238',
 'nir_frequencies239',
 'nir_frequencies240',
 'nir_frequencies241',
 'nir_frequencies242',
 'nir_frequencies243',
 'nir_frequencies244',
 'nir_frequencies245',
 'nir_frequencies246',
 'nir_frequencies247',
 'nir_frequencies248',
 'nir_frequencies249',
 'nir_frequencies250',
 'nir_frequencies251',
 'nir_frequencies252',
 'nir_frequencies253',
 'nir_frequencies254',
 'nir_frequencies255']

In [159]:
df_bw.drop(name_list, axis=1, inplace=True)

In [160]:
df_bw

,nir_mean,nir_median,nir_stdev,area,convex_hull_area,solidity,perimeter,width,height,longest_path,...,nir_frequencies210,nir_frequencies211,nir_frequencies212,nir_frequencies213,nir_frequencies214,nir_frequencies216,center_of_mass0,center_of_mass1,ellipse_center0,ellipse_center1
0,37.554685,34.0,13.459041,3191.0,4068.0,0.784415,634.673527,174,37,1096,...,0,0,0,0,0,0,661.206518,716.185208,672.862244,714.586426
1,60.327510,46.0,36.801379,45052.0,178591.0,0.252264,3044.372918,611,431,4168,...,0,0,0,0,0,0,707.989257,478.745161,714.550110,528.597351
2,58.813832,44.0,37.958030,47715.0,148611.0,0.321073,2471.103805,411,477,3564,...,0,0,0,0,0,0,658.262161,444.421042,576.378296,500.127045
3,84.551197,46.0,68.811036,5303.0,5899.5,0.898890,508.066015,219,38,1412,...,0,0,0,0,0,0,684.715067,715.408637,682.368225,714.712585
4,62.046977,45.0,42.304119,62094.0,203417.0,0.305255,4020.970021,577,515,3904,...,0,0,0,0,0,0,820.912020,431.798499,815.368896,505.041443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,60.908476,37.0,49.117656,95538.0,245156.5,0.389702,5324.429713,506,589,4798,...,0,0,0,0,0,0,917.996043,424.606649,854.520020,449.581421
990,65.389568,44.0,47.992251,80217.0,206081.5,0.389249,4973.995415,507,657,4816,...,0,0,0,0,0,0,878.042958,358.853310,848.194763,429.562134
991,68.491876,43.0,51.960883,75767.0,139274.5,0.544012,5135.419242,383,526,3743,...,0,0,0,0,0,0,710.262291,451.283791,719.425110,465.478058
992,73.719007,47.0,52.950624,31620.0,77629.5,0.407319,3019.457420,281,403,3122,...,0,0,0,0,0,0,741.120936,529.499273,724.179016,539.669312
993,64.519922,45.0,45.232740,19878.0,57668.0,0.344697,1732.060087,389,262,2879,...,0,0,0,0,0,0,776.597394,597.696800,773.558167,609.145569

In [161]:
df_labels = pd.read_csv("data/seedling_labels.csv")
df_labels

,Expert 1,Expert 2,Expert 3,Expert 4,color_cam_path,side_cam_path,Rfid,Pos
0,4,4,4,4,A1/00387 Plant 0000 Plant 0000/18-02-2019 -- 1...,A1/00387 Plant 0000 Plant 0000/18-02-2019 -- 1...,A1,Plant 0000
1,1,1,1,1,A1/00388 Plant 0001 Plant 0001/18-02-2019 -- 1...,A1/00388 Plant 0001 Plant 0001/18-02-2019 -- 1...,A1,Plant 0001
2,1,1,1,1,A1/00389 Plant 0002 Plant 0002/18-02-2019 -- 1...,A1/00389 Plant 0002 Plant 0002/18-02-2019 -- 1...,A1,Plant 0002
3,4,4,3,3,A1/00390 Plant 0003 Plant 0003/18-02-2019 -- 1...,A1/00390 Plant 0003 Plant 0003/18-02-2019 -- 1...,A1,Plant 0003
4,3,1,1,1,A1/00391 Plant 0004 Plant 0004/18-02-2019 -- 1...,A1/00391 Plant 0004 Plant 0004/18-02-2019 -- 1...,A1,Plant 0004
...,...,...,...,...,...,...,...,...
989,1,1,1,1,B4/01019 Plant 0122 Plant 0122/18-02-2019 -- 1...,B4/01019 Plant 0122 Plant 0122/18-02-2019 -- 1...,B4,Plant 0122
990,1,1,1,1,B4/01020 Plant 0123 Plant 0123/18-02-2019 -- 1...,B4/01020 Plant 0123 Plant 0123/18-02-2019 -- 1...,B4,Plant 0123
991,1,1,1,1,B4/01021 Plant 0124 Plant 0124/18-02-2019 -- 1...,B4/01021 Plant 0124 Plant 0124/18-02-2019 -- 1...,B4,Plant 0124
992,2,3,3,3,B4/01022 Plant 0125 Plant 0125/18-02-2019 -- 1...,B4/01022 Plant 0125 Plant 0125/18-02-2019 -- 1...,B4,Plant 0125
993,3,3,3,3,B4/01023 Plant 0126 Plant 0126/18-02-2019 -- 1...,B4/01023 Plant 0126 Plant 0126/18-02-2019 -- 1...,B4,Plant 0126

In [162]:
#remove the same rows as above
df_labels.drop([719, 826, 836, 919, 962, 982], axis=0, inplace=True)

In [163]:
df_labels = df_labels.iloc[:, : 4]
df_labels

     Expert 1  Expert 2  Expert 3  Expert 4
0           4         4         4         4
1           1         1         1         1
2           1         1         1         1
3           4         4         3         3
4           3         1         1         1
..        ...       ...       ...       ...
989         1         1         1         1
990         1         1         1         1
991         1         1         1         1
992         2         3         3         3
993         3         3         3         3

[988 rows x 4 columns]

In [164]:
dataframes = [df_labels,df_bw]
final = pd.concat(dataframes,axis = 1)
final

,Expert 1,Expert 2,Expert 3,Expert 4,nir_mean,nir_median,nir_stdev,area,convex_hull_area,solidity,...,nir_frequencies210,nir_frequencies211,nir_frequencies212,nir_frequencies213,nir_frequencies214,nir_frequencies216,center_of_mass0,center_of_mass1,ellipse_center0,ellipse_center1
0,4,4,4,4,37.554685,34.0,13.459041,3191.0,4068.0,0.784415,...,0,0,0,0,0,0,661.206518,716.185208,672.862244,714.586426
1,1,1,1,1,60.327510,46.0,36.801379,45052.0,178591.0,0.252264,...,0,0,0,0,0,0,707.989257,478.745161,714.550110,528.597351
2,1,1,1,1,58.813832,44.0,37.958030,47715.0,148611.0,0.321073,...,0,0,0,0,0,0,658.262161,444.421042,576.378296,500.127045
3,4,4,3,3,84.551197,46.0,68.811036,5303.0,5899.5,0.898890,...,0,0,0,0,0,0,684.715067,715.408637,682.368225,714.712585
4,3,1,1,1,62.046977,45.0,42.304119,62094.0,203417.0,0.305255,...,0,0,0,0,0,0,820.912020,431.798499,815.368896,505.041443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,1,1,1,1,60.908476,37.0,49.117656,95538.0,245156.5,0.389702,...,0,0,0,0,0,0,917.996043,424.606649,854.520020,449.581421
990,1,1,1,1,65.389568,44.0,47.992251,80217.0,206081.5,0.389249,...,0,0,0,0,0,0,878.042958,358.853310,848.194763,429.562134
991,1,1,1,1,68.491876,43.0,51.960883,75767.0,139274.5,0.544012,...,0,0,0,0,0,0,710.262291,451.283791,719.425110,465.478058
992,2,3,3,3,73.719007,47.0,52.950624,31620.0,77629.5,0.407319,...,0,0,0,0,0,0,741.120936,529.499273,724.179016,539.669312
993,3,3,3,3,64.519922,45.0,45.232740,19878.0,57668.0,0.344697,...,0,0,0,0,0,0,776.597394,597.696800,773.558167,609.145569

In [165]:
final.to_csv("Grayscale_Features_Cleaned.csv")